/**
 * AUDIT-11 §12: the rarity source for "seen in N% of Games" badges.
 *
 * Runs the default config across the shipped arenas and records, for every
 * structured `EventType`, the share of Games in which it appeared at least
 * once. Writes `src/data/beatRarity.ts`. Only types seen in fewer than
 * `KEEP_BELOW` of Games are kept — the badge is for rare beats.
 *
 *   BEAT_RUNS=400 npx tsx scripts/measure-beat-rarity.ts
 */
import { writeFileSync } from 'fs';
import { Simulator } from '../src/engine/simulator';
import { ARENAS, DEFAULT_GAME_CONFIG } from '../src/data/constants';
import { initialRunState } from './runInit';

const RUNS = Number(process.env.BEAT_RUNS ?? 400);
const KEEP_BELOW = 0.1;
const seen = new Map<string, number>();
const arenaIds = ARENAS.map(a => a.id);

for (let i = 0; i < RUNS; i++) {
    const sim = new Simulator(initialRunState({
        seed: `BEAT${i}`, arenaId: arenaIds[i % arenaIds.length], config: DEFAULT_GAME_CONFIG,
    }));
    sim.processTraining();
    let guard = 3000;
    while (!sim.isFinished() && guard-- > 0) if (!sim.advance()) break;
    const types = new Set(sim.getState().log.map(l => l.type).filter((t): t is NonNullable<typeof t> => !!t));
    types.forEach(t => seen.set(t, (seen.get(t) ?? 0) + 1));
}

const rows = [...seen.entries()]
    .map(([type, n]) => [type, Math.round((n / RUNS) * 1000) / 10] as const)
    .filter(([, pct]) => pct < KEEP_BELOW * 100)
    .sort((a, b) => a[1] - b[1]);

const body = `/**
 * AUDIT-11 §12: share of Games (percent) in which each rare structured beat
 * appears at least once. GENERATED by \`scripts/measure-beat-rarity.ts\` over
 * ${RUNS} default-config runs; regenerate after changing what the engine logs.
 * Only beats seen in fewer than ${KEEP_BELOW * 100}% of Games are listed.
 */
export const BEAT_RARITY_RUNS = ${RUNS};

export const BEAT_RARITY: Record<string, number> = {
${rows.map(([t, p]) => `    '${t}': ${p},`).join('\n')}
};

/** "seen in 0.3% of Games", or undefined for a beat that is not rare. */
export function beatRarityLabel(type: string | undefined): string | undefined {
    if (!type) return undefined;
    const pct = BEAT_RARITY[type];
    if (pct === undefined) return undefined;
    return pct === 0 ? 'never seen in measurement' : \`seen in \${pct}% of Games\`;
}
`;
writeFileSync('src/data/beatRarity.ts', body);
console.log(`beat rarity: ${rows.length} rare types of ${seen.size} over ${RUNS} runs`);
rows.forEach(([t, p]) => console.log(`  ${t.padEnd(28)} ${p}%`));
