/**
 * AUDIT-11 §12: share of Games (percent) in which each rare structured beat
 * appears at least once. GENERATED by `scripts/measure-beat-rarity.ts` over
 * 300 default-config runs; regenerate after changing what the engine logs.
 * Only beats seen in fewer than 10% of Games are listed.
 */
export const BEAT_RARITY_RUNS = 300;

export const BEAT_RARITY: Record<string, number> = {
    'expulsion': 0.3,
    'parachute-lost': 1.7,
    'loyal-broke': 3.3,
    'parachute-collected': 3.7,
    'waterborne-illness': 4,
    'fracture': 4,
    'treaty-outgrown': 4.3,
    'hearing': 5.7,
    'trap-destroyed': 6.3,
    'career-defections': 7,
    'treaty-renewed': 7,
    'faction-coups': 8.3,
    'succession-split': 9.7,
    'schism': 9.7,
};

/** "seen in 0.3% of Games", or undefined for a beat that is not rare. */
export function beatRarityLabel(type: string | undefined): string | undefined {
    if (!type) return undefined;
    const pct = BEAT_RARITY[type];
    if (pct === undefined) return undefined;
    return pct === 0 ? 'never seen in measurement' : `seen in ${pct}% of Games`;
}
